name: qt build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v2
        - name: configure qt 5.15.0
          uses: jurplel/install-qt-action@v2
          with:
            version: '5.15.0'
        - name: clean
          uses: make clean
        - name: qmake in release mode
          uses: qmake -config release LibDS/examples/SimpleDS/SimpleDS.pro
        - name: make
          uses: make
